### PR TITLE
Sponsor page update

### PR DESCRIPTION
**Pull request by loicmurumba**
## Changes Made

- Systems design dept. moved to Supporters Tier
- Patrons tier hidden ( we have no patrons ) 
- Waterloo North Hydro removed
- Husky Removed
- Dept of CS moved to Benefactor tier
- Samuel and Son Logo new logo and moved to benefactor ( logo is in the marketing room)
- Move Benefactors to be 2 logos wide so they are larger
- Associates 3 logos wide
- Supporters backers 4 logos wide

### CODE REVIEW

**Review by STBTony — CHANGES_REQUESTED** [review]
image
Mobile views break completely. Need to review the changes done on bootstrapping

**Comment by STBTony** [comment]
image
Need to make it more responsive.
Below is the current mobile view live:
image

**Comment by STBTony** [comment]
@loicmurumba @MinghaoJ we could push out a separate pr simply for the image swap. This way we get to put out the emergency fire first.

**Comment by loicmurumba** [comment]
@STBTony I fixed the mobile non responsiveness

**Review by STBTony — APPROVED** [review]

**Pull request merged**
